name: Build and Upload artifacts
on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz
          - target: x86_64-apple-darwin
            archive: zip
    steps:
      - name: Install ncurses
        run: sudo apt-get install -y libncurses5 libncurses5-dev
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@6694d4a74d687379a2e9780def73228afa87dae8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}